config/routes.rb
Blog::Application.routes.draw do

  resources :users, :except => [:new, :create, :index] do
    get 'toggle_poker_player', :on => :member
  end

  resources :posts do
    resources :comments
  end
  match '/feed' => 'news_items#feed', :as => :feed, :defaults => { :format => 'atom' }

  resources :albums do
    resources :photos
  end
  match 'picture_frame' => 'picture_frame#show', :as => 'picture_frame'
  match 'picture_frame/:id/update' => 'picture_frame#update', :as => 'picture_frame_update'

  resources :tournaments, :except => [:edit, :update] do
    put 'rsvp', :on => :member
  end

  resources :players, :only => [:update, :create]

  #omniauth
  match "/auth/:provider/callback" => 'sessions#create'
  match "/signout" => 'sessions#destroy', :as => :signout

  root :to => 'posts#index', :as => :home
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :user
  belongs_to :commentable, :polymorphic => true

  validates_presence_of :user_id, :content

  default_scope :order => 'created_at ASC'

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  set_tab :blog

  before_filter :authenticated?, :except => [:index, :show]

  def new
    @post = Post.find_by_web_title params[:post_id]
    @comment = Comment.new
  end

  def edit
    @post = Post.find_by_web_title params[:post_id]
    @comment = Comment.find params[:id]
  end

  def create
    @post = Post.find_by_web_title params[:post_id]
    @comment = Comment.new(params[:comment])
    @comment.user_id = @current_user.id
    @comment.commentable_id = @post.id
    @comment.commentable_type = @post.class.name
    if @comment.save
      Notifier.new_comment(@comment, @post).deliver
      redirect_to post_path @post
    else
      render :action => 'new'
    end
  end

  def update
    @post = Post.find_by_web_title params[:post_id]
    @comment = Comment.find params[:id]
    @comment.attributes = params[:content]
    if @comment.save
      redirect_to post_path @post
    else
      render :action => 'edit'
    end
  end

end

app/views/comments/_comment.html.haml
= form_for [@post, comment], :url => post_comments_path(:post_id => params['id']) do |form|
  %p
    %table
      %tr
        - options = current_user.nil? ? {:disabled => 'disabled'} : {}
        %td{:style => 'align: left;'}= form.text_area :content, options.merge({:style => 'width: 400px; height: 50px'})
        %td{:style => 'width: 100%;'}= form.submit 'Post', options

app/views/comments/_index.html.haml
%table
  %tr
    %td{:style => 'width: 100%; vertical-align: bottom;'}
      %h1{:style => 'margin: 0 0 0 0;'}
        = 'Comments'
%hr
  = render :partial => 'comments/comment', :locals => {:comment => Comment.new(:content => (current_user.nil? ? 'Sign in to post a comment.' : ''))}
%table
  -comments.each do |comment|
    %tr{:class => cycle("even", "odd")}
      %td{:style => 'width: 30%;'}
        =comment.user.name
      %td{:style => 'width: 70%;'}
        =comment.content