config/routes.rb
Blog::Application.routes.draw do

  resources :users, :except => [:new, :create, :index] do
    get 'toggle_poker_player', :on => :member
  end

  resources :posts do
    resources :comments
  end
  match '/feed' => 'news_items#feed', :as => :feed, :defaults => { :format => 'atom' }

  resources :albums do
    resources :photos
  end
  match 'picture_frame' => 'picture_frame#show', :as => 'picture_frame'
  match 'picture_frame/:id/update' => 'picture_frame#update', :as => 'picture_frame_update'

  resources :tournaments, :except => [:edit, :update] do
    put 'rsvp', :on => :member
  end

  resources :players, :only => [:update, :create]

  #omniauth
  match "/auth/:provider/callback" => 'sessions#create'
  match "/signout" => 'sessions#destroy', :as => :signout

  root :to => 'posts#index', :as => :home
end

app/views/notifier/error.html.haml
%p=@time
%p=@user.name
%p=@message

app/views/notifier/new_comment.html.haml
%p= @comment.content

= post_url(@object) if @comment.commentable_type == 'Post'

app/views/notifier/new_photo.html.haml
= album_photo_url(@photo.album, @photo)

app/views/notifier/new_tournament.html.haml
%p
  = "Please "
  = link_to 'RSVP', tournament_url(@tournament)
  = " even if you can't make it."
%h3= "Latest games:" unless @recent_tournaments.empty?
%table
  - @recent_tournaments.each do |tournament|
    %tr
      %td= link_to(tournament.name, tournament_url(tournament))
%h3
  My address is:
206 Scheer Ave.
%br
Durham, NC 27703
%h3
  My phone number is:
(919) 649-8587
%h3
  Rules:
Texas hold-em no-limit poker.
%br
Blinds start at 7:15.
%br
$20 buy in.
%br
Blinds start at $0.25/$0.50 and double every 20 minutes
%br
Unlimited re-buys before the blinds become $1/$2
%br
You have the option to 'add-on' when the blinds become $1/$2.
%br
2nd place gets $40.
%br
1st place gets the rest of the pot.
%br
%br
BYOB.
%br
Cigars are cool.