config/routes.rb
Blog::Application.routes.draw do

  resources :users, :except => [:new, :create, :index] do
    get 'toggle_poker_player', :on => :member
  end

  resources :posts do
    resources :comments
  end
  match '/feed' => 'news_items#feed', :as => :feed, :defaults => { :format => 'atom' }

  resources :albums do
    resources :photos
  end
  match 'picture_frame' => 'picture_frame#show', :as => 'picture_frame'
  match 'picture_frame/:id/update' => 'picture_frame#update', :as => 'picture_frame_update'

  resources :tournaments, :except => [:edit, :update] do
    put 'rsvp', :on => :member
  end

  resources :players, :only => [:update, :create]

  #omniauth
  match "/auth/:provider/callback" => 'sessions#create'
  match "/signout" => 'sessions#destroy', :as => :signout

  root :to => 'posts#index', :as => :home
end

app/models/photo.rb
require 'paperclip'

class Photo < ActiveRecord::Base
  belongs_to :uploaded_by, :foreign_key => 'user_id', :class_name => 'User'
  belongs_to :album

  validates_presence_of             :user_id
  validates_attachment_presence     :image
  validates_attachment_size         :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/gif', 'image/jpeg', 'image/png']

  has_attached_file :image,
    :storage             => :s3,
    :bucket              => S3_BUCKET_NAME,
    :s3_credentials      => {
      :access_key_id     => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']},
    :styles              => {
      :large             => "1280x800",
      :medium            => "700x400",
      :thumb             => "100x60"},
    :convert_options     => { :all => '-auto-orient' },
    :path                => ":style/:basename.:extension"

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  set_tab :picture_frame

  before_filter :authenticated?, :except => [:show]

  def create
    @photo = Photo.new(params[:photo])
    @photo.album = Album.find_by_name 'New' unless current_user.admin?
    @photo.uploaded_by = current_user
    if @photo.save
      PictureFrame.replace_displayed_with(@photo)
      Notifier.new_photo(@photo).deliver
      redirect_to albums_path
    else
      redirect_to albums_path
    end
  end

  def show
    @photo = Photo.find_by_id params[:id]
  end

  def edit
    @photo = Photo.find_by_id params[:id]
    PictureFrame.replace_displayed_with(@photo)
    logger.info "#{@photo} displayed by #{current_user.name}"
    redirect_to picture_frame_show_path
  end

end

app/views/photos/_photo.html.haml
%div{:style => 'text-align: center'}
  -#- if current_user.special_access?
  %p{:class => 'info'}
    Upload a picture and it will be displayed on my 'in-home' digital picture frame.
  -#- else
    %p{:class => 'info'}
      User's are allowed to upload one picture each.  This picture will be displayed on my 'in-home' digital picture frame.
  = form_for [album, photo], :html => {:multipart => true} do |form|
    %table{:style => 'margin-left:auto; margin-right:auto;'}
      - if current_user && current_user.admin?
        %tr
          %td= label :album, 'Album:'
          %td= form.select :album_id, options_from_collection_for_select(Album.all, "id", "name")
      %tr
        %td= label :image, 'Photo:'
        %td= form.file_field :image
        %td= form.submit 'Upload'

app/views/photos/show.html.haml
%div{:style => 'text-align: center'}
  = link_to 'Display this image on my in-home picture frame', picture_frame_update_path(:id => @photo.id)
  %br
  = image_tag(@photo.image.url(:medium))