config/routes.rb
Blog::Application.routes.draw do

  resources :users, :except => [:new, :create, :index] do
    get 'toggle_poker_player', :on => :member
  end

  resources :posts do
    resources :comments
  end
  match '/feed' => 'news_items#feed', :as => :feed, :defaults => { :format => 'atom' }

  resources :albums do
    resources :photos
  end
  match 'picture_frame' => 'picture_frame#show', :as => 'picture_frame'
  match 'picture_frame/:id/update' => 'picture_frame#update', :as => 'picture_frame_update'

  resources :tournaments, :except => [:edit, :update] do
    put 'rsvp', :on => :member
  end

  resources :players, :only => [:update, :create]

  #omniauth
  match "/auth/:provider/callback" => 'sessions#create'
  match "/signout" => 'sessions#destroy', :as => :signout

  root :to => 'posts#index', :as => :home
end

app/views/layouts/_ga.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32547752-1']);
  _gaq.push(['_setSiteSpeedSampleRate', 100]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/application.html.haml
%html
  %head
    %title= @post ? @post.title : 'Three programmers walked into a bar...'
    %link{:rel => "shortcut icon", :href => "/images/favicon.ico"}
    -# Without csrf_meta_tag AJAX requests create a new session
    -# referrence: http://joshhuckabee.com/jquery-rails-3
    = csrf_meta_tag
    = auto_discovery_link_tag(:rss, "#{posts_path}.rss")
    = stylesheet_link_tag "application"
    = stylesheet_link_tag "social-share-button"
    = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css"
    = javascript_include_tag "application"
  %body
    %table{:class => 'main'}
      %tr
        %td
          %div#header{:id => 'header', :class => 'header'}
            - if flash[:notice]
              %span{:class => 'notice'}
                = flash[:notice]
            - if flash[:alert]
              %span{:class => 'error'}
                = flash[:alert]
            %div
              %div#user_nav{:class => 'user_nav'}
                - if current_user
                  %div#sign_out{:class => 'sign_out'}
                    = "Welcome #{current_user.name} | "
                    = link_to "Sign out", signout_path
                - else
                  %div#sign_in{:class => 'sign_in'}
                    Sign in with
                    %a{:href => '/auth/google', :id => 'auth_google'}
                      = image_tag('google_32.png', :align => :absmiddle)
                    %a{:href => '/auth/twitter', :id => 'auth_twitter'}
                      = image_tag('twitter_32.png', :align => :absmiddle)
            %div#title{:class => 'title'}
              %a{:href => home_path}
                Three programmers
                %br
                walked into a bar...
            %div#tabs
              = tabs_tag do |tab|
                = tab.blog 'Blog', home_path
                = tab.poker 'Poker', tournaments_path
                = tab.picture_frame 'Picture Frame', albums_path
      %tr
        %td
          %div#subtabs
            = yield :subtabs
      %tr
        %td
          %div#content{:class => 'content'}
            - if current_tab == :blog
              %div{:class => 'feeds'}
                %div
                  Follow me on Twitter
                  = link_to( image_tag('twitter_16.png', :align => :baseline), 'http://twitter.com/gposton', :id => 'twitter')
                %div
                  Subscribe to my RSS feed
                  = link_to( image_tag('rss_16.png', :align => :baseline), 'http://feeds.feedburner.com/ThreeProgrammersWalkedIntoABar', :id => 'rss_feed')
            = yield
    = render :partial => 'layouts/ga' if Rails.env == 'production'

app/views/layouts/posts.html.haml
- content_for :subtabs do
  %span
    = tabs_tag :namespace => :subtabs do |tab|
      = tab.all 'All', posts_path
      - Tag.all.each do |tag|
        -#TODO: load posts in initial sql call
        = tab.send(tag.name, tag.name.capitalize, "#{posts_path}?tag=#{tag.to_param}") unless tag.posts.empty?
= render :file => 'layouts/application'

app/views/layouts/tournaments.html.haml
- content_for :subtabs do
  %span
    = tabs_tag :namespace => :subtabs do |tab|
      - unless current_user.poker_player?
        = tab.register 'Register', poker_registration_path
      - else
        = tab.all 'All tournaments', tournaments_path
        = tab.my_tournaments 'My tournaments', current_user
        = tab.register 'Unsubscribe', toggle_poker_player_user_path(current_user)
        = tab.change_email 'Update email', edit_user_path(current_user)
= render :file => 'layouts/application'